# Same as examples/basic-raw/basic-raw.yaml
type: "raw"
requests:
  - request:
    id: "1"
    methods: ["GET", "POST"]
    endpoint: "/"
    response-type: "raw"
    content-type: "text/html"
    content:
      |
      <html>
      <head>
        <title>Hello</title>
      </head>
      <body>
        <h1>Hello!</h1>
      </body>
      </html>
    headers:
      - "server: Akamai Resource Optimizer"
      - "server-timing: cdn-cache; desc=HIT"
  - request:
    id: "default"
    response-type: "file"
    content-type: "text/html"
    content: "404.html"
    headers:
      - "server: Akamai Resource Optimizer"
      - "server-timing: cdn-cache; desc=HIT"

ignore: ["/favicon.ico"]
