version: "3"

services:

  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    volumes:
      - /mongo-volume:/data/db
    ports:
      - "27017:27017"
    restart: always

  boggart:
    restart: always
    build: .
    ports:
      - "8092:8092"
