version: "3"

services:

  mongo:
    container_name: mongo
    image: "mongo:latest"
    expose:
      - "27017"
    restart: always
    volumes:
      - "/mongo-volume:/data/db"

  boggart:
    build: "."
    depends_on:
      - 'mongo'
    ports:
      - "8092:8092" #honeypot
      - "8094:8094" #API
    restart: always
